version: '3.8'
services:
  fastapi:
    build: .
    container_name: fastapi-app
    environment:
      PORT: 8000
    ports:
      - '8000:8000'
  mongo:
    ports:
      - '27017:27017'
    container_name: mongoContainer
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123
    image: mongo:latest
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - type: volume
        source: cache
        target: /cacheData

volumes:
  cache:
    driver: local

